### **Python NumPy Array**  
* numerical python  
* it is very fast compare to python range   
    fully used array[],0D,1D, 2D,3D
  
  0D(ZERO DIMENTIOANL)= .(no width,height)=[10]
  
  1D(vector array)---[10,20,30,40,50]=>shape(1,4)
  
  2D(matrix array)---[[10,20,30,40],[11,12,13,14]]=>shape(2,4)  

  3D(matrix array)---[[[10,20,30,40],[50,60,70,80]],[[10,20,30,40],[50,60,70,80]]]=>
     

In [1]:
!pip install numpy

In [3]:
import numpy as np

In [24]:
#1D array

array_1=np.array([10,20,30])

print(array_1)
print(array_1.shape)
print(array_1.size)
array_1.ndim  # to find what dimentional
array_1.dtype # to find what data type

[10 20 30]
(3,)
3


dtype('int64')

In [22]:
#2D array

array_2 = np.array([[10,20,30],
                    [40,50,60],
                    [70,80,90]])
print(array_2)
print(array_2.shape)
print(array_2.size)
array_2.ndim
array_2.dtype

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)
9


2

In [26]:
#3D array

array_3 = np.array([[[10,20,30],[10,20,30],[10,20,30]],
                    [[40,50,60],[40,50,60],[40,50,60]]])
print(array_3)
print(array_3.shape)
array_3.size
array_3.ndim
array_3.dtype

[[[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[40 50 60]
  [40 50 60]
  [40 50 60]]]
(2, 3, 3)


dtype('int64')

In [ ]:
# type casting

In [29]:
array_2 = np.array([[10,20,30],
                    [40,50,60],
                    [70,"hai",90]])
print(array_2) 
print(array_2.dtype) 

#<U21 means under 21 bits

[['10' '20' '30']
 ['40' '50' '60']
 ['70' 'hai' '90']]
<U21


In [30]:
# to change ini value 

array_2 = np.array([[10,20,30],
                    [40,50,60],
                    [70,"hai",90]],dtype="int")
print(array_2) 
print(array_2.dtype) 

ValueError: invalid literal for int() with base 10: 'hai'

In [31]:
array_2 = np.array([[10,20,30],
                    [40,50,60],
                    [70,"100",90]],dtype="int")
print(array_2) 
print(array_2.dtype) 

[[ 10  20  30]
 [ 40  50  60]
 [ 70 100  90]]
int64


In [32]:

#to change float
array_2 = np.array([[10,20,30],
                    [40,50,60],
                    [70,"100",90]],dtype="float")
print(array_2) 
print(array_2.dtype) 

[[ 10.  20.  30.]
 [ 40.  50.  60.]
 [ 70. 100.  90.]]
float64


### **Array filling --(.full)**

In [44]:
# a=np.full((5,5),2)

# or
# a=np.full((5,5),[1,2,3,4,5])
a=np.full((5,5),['B','A','B','Y','G'])
print(a)
print(a.dtype)

[['B' 'A' 'B' 'Y' 'G']
 ['B' 'A' 'B' 'Y' 'G']
 ['B' 'A' 'B' 'Y' 'G']
 ['B' 'A' 'B' 'Y' 'G']
 ['B' 'A' 'B' 'Y' 'G']]
<U1


In [39]:
b=np.full((2,3,4),4)  
print(b)
print(b.dtype)


[[[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]

 [[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]]
int64


In [47]:
c=np.zeros((5,5),dtype="int") 
print(c)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [50]:
d=np.ones((5,5),dtype="int") 
print(d)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### **Arange**

In [57]:
# python

for each in range(-10,11,2):
   print(each,end=" ")

-10 -8 -6 -4 -2 0 2 4 6 8 10 

In [58]:
# numpy

x = np.arange(-10,11,2)
print(x)

[-10  -8  -6  -4  -2   0   2   4   6   8  10]


In [59]:
print(np.arange(-10,11,2))

[-10  -8  -6  -4  -2   0   2   4   6   8  10]


In [63]:
print(np.arange(100,0,-10))

[100  90  80  70  60  50  40  30  20  10]


### **linspace**

In [66]:
x=np.linspace(0,100,100)
print(x)

[  0.           1.01010101   2.02020202   3.03030303   4.04040404
   5.05050505   6.06060606   7.07070707   8.08080808   9.09090909
  10.1010101   11.11111111  12.12121212  13.13131313  14.14141414
  15.15151515  16.16161616  17.17171717  18.18181818  19.19191919
  20.2020202   21.21212121  22.22222222  23.23232323  24.24242424
  25.25252525  26.26262626  27.27272727  28.28282828  29.29292929
  30.3030303   31.31313131  32.32323232  33.33333333  34.34343434
  35.35353535  36.36363636  37.37373737  38.38383838  39.39393939
  40.4040404   41.41414141  42.42424242  43.43434343  44.44444444
  45.45454545  46.46464646  47.47474747  48.48484848  49.49494949
  50.50505051  51.51515152  52.52525253  53.53535354  54.54545455
  55.55555556  56.56565657  57.57575758  58.58585859  59.5959596
  60.60606061  61.61616162  62.62626263  63.63636364  64.64646465
  65.65656566  66.66666667  67.67676768  68.68686869  69.6969697
  70.70707071  71.71717172  72.72727273  73.73737374  74.74747475
  75.7575757

### **nan,inf**

In [71]:
# nan

# python-->want to import math

import math as m

print(m.sqrt(10))
print(m.sqrt(-10)) # dont do negative value
print("hello")

3.1622776601683795


ValueError: math domain error

In [75]:
#numpy array

print(np.sqrt(10))

print(np.sqrt(-10)) # execute,sgives only nan 

print("hello")

3.1622776601683795
nan
hello


C:\Users\Admin\AppData\Local\Temp\ipykernel_19408\1087484280.py:4: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-10))


In [78]:
# inf
# python
print(10/2)
print(10/0) #ZeroDivisionError

print("hello")

5.0


ZeroDivisionError: division by zero

In [84]:
# numpy array
x=np.array([10])/2
print(x)
print("hello")

[5.]
hello


In [85]:
print(np.array([10])/2)
print(np.array([10])/0)
print("hello")

[5.]
[inf]
hello


C:\Users\Admin\AppData\Local\Temp\ipykernel_19408\1347866918.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10])/0)
